# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='desciption',
            new_name='description',
        ),
    ]
